### ISSUE TITLE
Where are the control_type{i} files and how are they generated?

### ISSUE THREAD

**Issue by oqusous** [ShuyangCao/open-ended_question_ontology#4]
Hi,

Thank you for responding to my earlier issue. Really appreciate it. I managed to generate questions using the `explgen.sh` and `jointgen.sh`. 

I could not do the same for 'tplgen_question_generation.sh', 'explgen_9types.sh' and 'tplgen_question_generation_9types.sh'. The following errors popped-up. Can you please tell me what your thoughts are?

### 'tplgen_question_generation.sh'
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 392, in cli_main
    main(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 48, in main
    return _main(cfg, h)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 107, in _main
    task.load_dataset(cfg.dataset.gen_subset, task_cfg=saved_cfg.task)
  File "/home/ubuntu/qg/fairseq_models/tplgen_qg/tplgen_qg_task.py", line 344, in load_dataset
    self.datasets[split] = load_langpair_dataset(
  File "/home/ubuntu/qg/fairseq_models/tplgen_qg/tplgen_qg_task.py", line 142, in load_langpair_dataset
    template_dataset = AppendTokenDataset(template_dataset, src_dict.index('50256'))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq/data/append_token_dataset.py", line 17, in __init__
    self._sizes = np.array(dataset.sizes) + 1
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq/data/base_wrapper_dataset.py", line 30, in sizes
    return self.dataset.sizes
AttributeError: 'NoneType' object has no attribute 'sizes'
```
### 'explgen_9types.sh' and 'tplgen_question_generation_9types.sh'
The error is repeated for all types 1-9
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 392, in cli_main
    main(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 48, in main
    return _main(cfg, h)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 107, in _main
    task.load_dataset(cfg.dataset.gen_subset, task_cfg=saved_cfg.task)
  File "/home/ubuntu/qg/fairseq_models/jointgen/jointgen_task.py", line 421, in load_dataset
    self.datasets[split] = load_langpair_dataset(
  File "/home/ubuntu/qg/fairseq_models/jointgen/jointgen_task.py", line 200, in load_langpair_dataset
    qt_dataset = load_qt_data(qt_path, src_dict)
  File "/home/ubuntu/qg/fairseq_models/jointgen/jointgen_task.py", line 110, in load_qt_data
    with open(qt_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/binarized_data/jointgen_data/test.control_type9'
```
I was also comparing the binarized data folder your shared on g-drive and the data I was able to produce using the `data_processing` scripts script and found the following differences:

1. did not find the folder and all its contents: `data/binarized_data/exemplar_data/control_exemplar`
2. did not find the folder and all its contents: `data/binarized_data/focus_data/control_exemplar`
3. did not find the folder and all its contents: `data/binarized_data/template_data`

**Comment by ShuyangCao** [comment]
Hi, thanks for reaching out. I missed this part in the `data_preprocess`. Will add this part later this week and let you know about that.

**Comment by ShuyangCao** [comment]
Hi, please check the [added part](https://github.com/ShuyangCao/open-ended_question_ontology/commit/6b8c8ce10366e89eeb2b3a462c7b43e16dbfd2c9) of the README file. Let me know if you encounter any problems.

**Comment by ghost** [comment]
Hey,
I got the following from running:
```shell
./tplgen_template_generation.sh $DATA/output/tplgen_template
```
```
/home/ubuntu/.local/lib/python3.8/site-packages/hydra/experimental/initialize.py:35: UserWarning: hydra.experimental.initialize() is no longer experimental. Use hydra.initialize()
  deprecation_warning(
/home/ubuntu/.local/lib/python3.8/site-packages/hydra/experimental/compose.py:18: UserWarning: hydra.experimental.compose() is no longer experimental. Use hydra.compose()
  deprecation_warning(
/home/ubuntu/.local/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'config': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/ubuntu/.local/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/ubuntu/.local/bin/fairseq-generate:8: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
  sys.exit(cli_main())
Error when composing. Overrides: ['common.no_progress_bar=False', 'common.log_interval=100', 'common.log_format=null', 'common.tensorboard_logdir=null', 'common.wandb_project=null', 'common.seed=1', 'common.cpu=False', 'common.tpu=False', 'common.bf16=False', 'common.memory_efficient_bf16=False', 'common.fp16=False', 'common.memory_efficient_fp16=False', 'common.fp16_no_flatten_grads=False', 'common.fp16_init_scale=128', 'common.fp16_scale_window=null', 'common.fp16_scale_tolerance=0.0', 'common.min_loss_scale=0.0001', 'common.threshold_loss_scale=null', "common.user_dir='fairseq_models/jointgen'", 'common.empty_cache_freq=0', 'common.all_gather_list_size=16384', 'common.model_parallel_size=1', 'common.quantization_config_path=null', 'common.profile=False', 'common.reset_logging=True', "common_eval.path='models/generation_models/tplgen_template_generation/model.pt'", 'common_eval.post_process=null', 'common_eval.quiet=False', "common_eval.model_overrides='{}'", "common_eval.results_path='data_answers/output/tplgen_template'", 'distributed_training.distributed_world_size=1', 'distributed_training.distributed_rank=0', "distributed_training.distributed_backend='nccl'", 'distributed_training.distributed_init_method=null', 'distributed_training.distributed_port=-1', 'distributed_training.device_id=0', 'distributed_training.distributed_no_spawn=False', "distributed_training.ddp_backend='c10d'", 'distributed_training.bucket_cap_mb=25', 'distributed_training.fix_batches_to_gpus=False', 'distributed_training.find_unused_parameters=False', 'distributed_training.fast_stat_sync=False', 'distributed_training.broadcast_buffers=False', "distributed_training.distributed_wrapper='DDP'", 'distributed_training.slowmo_momentum=null', "distributed_training.slowmo_algorithm='LocalSGD'", 'distributed_training.localsgd_frequency=3', 'distributed_training.nprocs_per_node=1', 'distributed_training.pipeline_model_parallel=False', 'distributed_training.pipeline_balance=null', 'distributed_training.pipeline_devices=null', 'distributed_training.pipeline_chunks=0', 'distributed_training.pipeline_encoder_balance=null', 'distributed_training.pipeline_encoder_devices=null', 'distributed_training.pipeline_decoder_balance=null', 'distributed_training.pipeline_decoder_devices=null', "distributed_training.pipeline_checkpoint='never'", "distributed_training.zero_sharding='none'", 'distributed_training.tpu=False', 'dataset.num_workers=1', 'dataset.skip_invalid_size_inputs_valid_test=False', 'dataset.max_tokens=null', 'dataset.batch_size=16', 'dataset.required_batch_size_multiple=8', 'dataset.required_seq_len_multiple=1', 'dataset.dataset_impl=null', 'dataset.data_buffer_size=10', "dataset.train_subset='train'", "dataset.valid_subset='valid'", 'dataset.validate_interval=1', 'dataset.validate_interval_updates=0', 'dataset.validate_after_updates=0', 'dataset.fixed_validation_seed=null', 'dataset.disable_validation=False', 'dataset.max_tokens_valid=null', 'dataset.batch_size_valid=16', 'dataset.curriculum=0', "dataset.gen_subset='test'", 'dataset.num_shards=1', 'dataset.shard_id=0', 'optimization.max_epoch=0', 'optimization.max_update=0', 'optimization.stop_time_hours=0', 'optimization.clip_norm=0.0', 'optimization.sentence_avg=False', 'optimization.update_freq=[1]', 'optimization.lr=[0.25]', 'optimization.min_lr=-1.0', 'optimization.use_bmuf=False', "checkpoint.save_dir='checkpoints'", "checkpoint.restore_file='checkpoint_last.pt'", 'checkpoint.finetune_from_model=null', 'checkpoint.reset_dataloader=False', 'checkpoint.reset_lr_scheduler=False', 'checkpoint.reset_meters=False', 'checkpoint.reset_optimizer=False', "checkpoint.optimizer_overrides='{}'", 'checkpoint.save_interval=1', 'checkpoint.save_interval_updates=0', 'checkpoint.keep_interval_updates=-1', 'checkpoint.keep_last_epochs=-1', 'checkpoint.keep_best_checkpoints=-1', 'checkpoint.no_save=False', 'checkpoint.no_epoch_checkpoints=False', 'checkpoint.no_last_checkpoints=False', 'checkpoint.no_save_optimizer_state=False', "checkpoint.best_checkpoint_metric='loss'", 'checkpoint.maximize_best_checkpoint_metric=False', 'checkpoint.patience=-1', "checkpoint.checkpoint_suffix=''", 'checkpoint.checkpoint_shard_count=1', 'checkpoint.model_parallel_size=1', 'checkpoint.distributed_rank=0', 'bmuf.block_lr=1', 'bmuf.block_momentum=0.875', 'bmuf.global_sync_iter=50', 'bmuf.warmup_iterations=500', 'bmuf.use_nbm=False', 'bmuf.average_sync=False', 'bmuf.distributed_world_size=1', 'generation.beam=5', 'generation.nbest=1', 'generation.max_len_a=0', 'generation.max_len_b=100', 'generation.min_len=0', 'generation.match_source_len=False', 'generation.unnormalized=False', 'generation.no_early_stop=False', 'generation.no_beamable_mm=False', 'generation.lenpen=1.5', 'generation.unkpen=0', 'generation.replace_unk=null', 'generation.sacrebleu=False', 'generation.score_reference=False', 'generation.prefix_size=0', 'generation.no_repeat_ngram_size=0', 'generation.sampling=False', 'generation.sampling_topk=-1', 'generation.sampling_topp=-1.0', 'generation.constraints=null', 'generation.temperature=1.0', 'generation.diverse_beam_groups=-1', 'generation.diverse_beam_strength=0.5', 'generation.diversity_rate=-1.0', 'generation.print_alignment=False', 'generation.print_step=False', 'generation.lm_path=null', 'generation.lm_weight=0.0', 'generation.iter_decode_eos_penalty=0.0', 'generation.iter_decode_max_iter=10', 'generation.iter_decode_force_max_iter=False', 'generation.iter_decode_with_beam=1', 'generation.iter_decode_with_external_reranker=False', 'generation.retain_iter_history=False', 'generation.retain_dropout=False', 'generation.retain_dropout_modules=null', 'generation.decoding_format=null', 'generation.no_seed_provided=False', 'eval_lm.output_word_probs=False', 'eval_lm.output_word_stats=False', 'eval_lm.context_window=0', 'eval_lm.softmax_batch=9223372036854775807', 'interactive.buffer_size=0', "interactive.input='-'", 'criterion=cross_entropy', 'criterion._name=cross_entropy', "criterion.sentence_avg='${optimization.sentence_avg}'", 'lr_scheduler=fixed', 'lr_scheduler._name=fixed', 'lr_scheduler.force_anneal=null', 'lr_scheduler.lr_shrink=0.1', 'lr_scheduler.warmup_updates=0', "lr_scheduler.lr='${optimization.lr}'", 'scoring=bleu', 'scoring._name=bleu', 'scoring.pad=1', 'scoring.eos=2', 'scoring.unk=3']
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 392, in cli_main
    main(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 31, in main
    cfg = convert_namespace_to_omegaconf(cfg)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fairseq/dataclass/utils.py", line 344, in convert_namespace_to_omegaconf
    composed_cfg = compose("config", overrides=overrides, strict=False)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/hydra/experimental/compose.py", line 22, in compose
    return real_compose(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/hydra/compose.py", line 33, in compose
    cfg = gh.hydra.compose_config(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration_impl
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 378, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 730, in update
    assert isinstance(
AssertionError: Unexpected type for root: NoneType
```
From the errors it seems it is related to fairseq, My env:
```
pip install torch==1.7.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric==1.7.2
pip install git+git://github.com/pytorch/fairseq.git@0db28cdd0e50cad9c36e5e47ffceff40beaf6f60
```

**Comment by ShuyangCao** [comment]
Hi please install `hydra-core==1.0.6` and try again. There are some issues with the Fairseq requirement file.

**Comment by ghost** [comment]
Yes, that was the problem. If one starts from a fresh environment, downloading/installing fairseq commit from the commit specified in the readme misses 3 libraries:
hydra-core==1.0.7 (works as well)
bitarray-2.3.4
and touchaudio (which I presume is not required).

I also noticed that allennlp-models==1.1.0 was not mentioned which is needed too. Thank you very much.

**Comment by ghost** [comment]
### Running:
```
cd ../gen_scripts
./tplgen_template_generation_9types.sh $DATA/output/control_template
cd ..
python convert_output.py --generate-dir $DATA/output/tplgen_template/type*

for i in 1 2 3 4 5 6 7 8 9
do
  mkdir -p $DATA/binarized_data/template_data/control_template/type${i}
  cp $DATA/output/tplgen_template/type${i}/bpe-test.txt $DATA/binarized_data/template_data/control_template/type${i}/test.bpe.source
  cp $DATA/template_generation_data/oracle_raw/test.bpe.target $DATA/binarized_data/template_data/control_template/type${i}
  fairseq-preprocess --source-lang source --target-lang target \
    --testpref $DATA/binarized_data/template_data/control_template/type${i}/test.bpe \
    --destdir $DATA/binarized_data/template_data/control_template/type${i} \
    --workers 60 --srcdict dict.txt --tgtdict dict.txt
done
```
### Results with the following two errors:
1. cp command:
```
'data_answers/output/tplgen_template/type1/bpe-test.txt': No such file or directory  
```
2. fairseq-preprocess run:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data_answers/binarized_data/template_data/control_template/type1/test.bpe.source'
```
### `python convert_output.py --generate-dir $DATA/output/tplgen_template/type*` I do not think this generates any new output

### I also noticed the following typos (marked with ## next to line) in the `data_preprocess/README.md`:
```
python ../prediction_scripts/type_prediction_topk.py $MODEL/prediction_models/type_classifiers/answer_input/reddit \
  $DATA/raw_text/test_answer.txt $DATA/control_types
  
mkdir -p $DATA/question_exemplar/control
mkdir -p $DATA/exemplar_data/control
mkdir -p $DATA/binarized_data/exemplar_data/control_exemplar
for i in 1 2 3 4 5 6 7 8 9
do
  cp $DATA/control_types/control_type${i} $DATA/binarized_data/jointgen_data/test.control_type{i} ##=> control_type${i}
  cp $DATA/control_types/control_type${i} $DATA/binarized_data/tplgen_data/test.control_type{i} ##=> control_type${i}
  python ../prediction_scripts/exemplar_prediction.py $MODEL/prediction_models/exemplar_classifiers/reddit \
    $DATA/focus_prediction_data/oracle_raw/test.bpe.source $DATA/control_types/control_type${i} \
    $DATA/question_exemplar/control/control_type${i}
  mkdir -p $DATA/exemplar_data/control/type${i}
  python create_bpe_exemplar_data.py $DATA/question_exemplar/control/control_type${i} \
    $DATA/control_types/control_type${i} exemplars/exemplar_bpe.txt \
    $DATA/exemplar_data/control/type${i}/test.bpe.source
  mkdir -p $DATA/binarized_data/exemplar_data/control_exemplar/type${i}
  cp $DATA/exemplar_data/control/type${i}/* $DATA/binarized_data/exemplar_data/control_exemplar/type${i}
  cp $DATA/template_generation_data/oracle_raw/test.bpe.target $DATA/binarized_data/exemplar_data/control_exemplar/type${i}
  fairseq-preprocess --source-lang source --target-lang target \
    --testpref $DATA/binarized_data/exemplar_data/control_exemplar/type${i}/test.bpe \
    --destdir $DATA/binarized_data/exemplar_data/control_exemplar/type${i} \
    --workers 60 --srcdict dict.txt --tgtdict dict.txt
done
```
### And:
```
for i in 1 2 3 4 5 6 7 8 9
do
  mkdir -p $DATA/control_focus/type${i}
  python ../prediction_scripts/joint_focus_node_prediction.py $DATA/binarized_data/tplgen_data \
    --path $MODEL/generation_models/tplgen_template_generation/model.pt --user-dir ../fairseq_models/jointgen \
    --task joint_generation --qt control_type${i} --gen-subset test \
    --exemplar-data $DATA/binarized_data/exemplar_data/control_exemplar/type${i} --results-path $DATA/control_focus/type${i}/test.focus_prob
  python create_predicted_focus_data.py $DATA/control_focus/type${i}/test.focus_prob \
    $DATA/binarized_data/tplgen_data/test $DATA/question_focus/oracle/test.jsonl \
    $DATA/stanford_parsing_output/test_answer_converted.jsonl $DATA/control_focus/type${i}/test
  cp $DATA/template_generation_data/oracle_raw/${SPLIT}.bpe.target $DATA/control_focus/type${i} ##=> cp $DATA/template_generation_data/oracle_raw/test.bpe.target $DATA/control_focus/type${i}
  fairseq-preprocess --source-lang source --target-lang target \
    --testpref $DATA/control_focus/type${i}/test.bpe \
    --destdir $DATA/binarized_data/focus_data/control_focus/type${i} \
    --workers 60 --srcdict dict.txt --tgtdict dict.txt
done
```
Please let me know if my interpretation was correct. Thanks.

**Comment by ShuyangCao** [comment]
I fix the [typos](https://github.com/ShuyangCao/open-ended_question_ontology/commit/92ec92a12f2faeaf66b85d8e4d21d9119f1c4977). Forgot to replace `tplgen_template` with `control_template`.
