### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sizes'

### ISSUE THREAD

**Issue by dxlong2000** [ShuyangCao/open-ended_question_ontology#7]
Hi @ShuyangCao ,

Thanks for your great work. I have run ```./tplgen_template_generation.sh $DATA/output/tplgen_template``` and I got this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "../lib/fairseq/fairseq_cli/generate.py", line 392, in cli_main
    main(args)
  File "../lib/fairseq/fairseq_cli/generate.py", line 48, in main
    return _main(cfg, h)
  File "../lib/fairseq/fairseq_cli/generate.py", line 107, in _main
    task.load_dataset(cfg.dataset.gen_subset, task_cfg=saved_cfg.task)
  File "../fairseq_models/tplgen_qg/tplgen_qg_task.py", line 365, in load_dataset
    template_data=getattr(self.args, "template_data", None),
  File "../fairseq_models/tplgen_qg/tplgen_qg_task.py", line 142, in load_langpair_dataset
    template_dataset = AppendTokenDataset(template_dataset, src_dict.index('50256'))
  File "../lib/fairseq/fairseq/data/append_token_dataset.py", line 17, in __init__
    self._sizes = np.array(dataset.sizes) + 1
  File "../lib/fairseq/fairseq/data/base_wrapper_dataset.py", line 30, in sizes
    return self.dataset.sizes
AttributeError: 'NoneType' object has no attribute 'sizes'
```

Do you have any idea what causes this error?

Thanks!

**Comment by dxlong2000** [comment]
Hi @ShuyangCao I think you forgot the step to get ```$DATA/binarized_data/template_data/oracle```. Please update it soon.

Thanks!
Best regards,

**Comment by ShuyangCao** [comment]
Hi @dxlong2000 , the script works on my side. Can you check if the `--task` argument is set to `joint_generation` in your script?
